spring:
  application:
    name: greetings-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/greetings-service/

eureka:
  server:
    enableSelfPreservation: false
  client:
    serviceUrl:
      defaultZone: https://eureka-server-153892321326.us-central1.run.app/eureka
  instance:
    hostname: eureka-server-153892321326.us-central1.run.app
    ip-address: eureka-client-153892321326.us-central1.run.app
    nonSecurePort: 443
    preferIpAddress: false
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 35

management:
  server:
    port: 8080
    context-path: /
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
